[theme]
base="dark"
textColor="darkGoldenrod"
linkColor="darkOrchid"

[server]
runOnSave = true
fileWatcherType = "none"
maxWidgetStateSize = 25

[client]
disableDataExport = true

[browser]
gatherUsageStats = false